typography_spectrum: 0.1446
color:
  brandColors:
    - '#ffffff'
    - '#b83328'
    - '#5198ab'
    - '#000000'
    - '#4f5b60'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f9efb5d-89fb-433f-99e1-a7d017179838.png
name: Redshorts
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Redshorts Photography
purpose: []
