name: Redshorts
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b83328'
    - '#5198ab'
    - '#000000'
    - '#4f5b60'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
