name: Redshorts
favicon: null
layout_spectrum: 0.6218068313319236
typography_spectrum: 0.08476348128169775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4402681225910783
  lightness: 0.9443132048472762
  saturation: 0.9478386302944273
  rhythmicContrast: 0.6383016230538487
purpose: []
